---
title: "Regresión Lineal Simple: Prueba"
author: "Juan Barriola y Sofía Perini"
date: "19 de Septiembre de 2020"
output:
  html_notebook:
    theme: spacelab
    toc: yes
    toc_float: yes
    df_print: paged
---

# Encuesta de Sueldos en el sector IT

Vamos a trabajar con un dataset de openqube^[https://openqube.io/encuesta-sueldos-2020.01#Introduccion%20%20%20https://docs.google.com/spreadsheets/d/e/2PACX-1vTORpz5hc_wOwKdaKEIgVOAI3XVTh9WXB__C2abe_E0aJoYIoqhWQ-HTpBBryAByhIlX_booioqxK0T/pub?gid=1893349211&single=true&output=csv] sobre empleos en el sector IT.

```{r}
library(data.table)
library(tidyverse)
library(readxl) 
library(lubridate)
library(corrr)
library(knitr)
library(kableExtra)
library(GGally)
```

## Preparación de Datos

```{r}
encuesta <- read_csv("../Fuentes/Encuesta de remuneracion salarial - 2020.1.csv")
encuesta %>%
  glimpse()
encuesta %>%
  head(10)
unique(encuesta$`Estoy trabajando en`) # solo Argentina aparece
unique(encuesta$`Dónde estás trabajando`) # en qué parte del país

unique(encuesta$`Trabajo de`)
table(encuesta$`Trabajo de`)
```

### Filtros 

Se seleccionan las variables de interes.

```{r}
df1 <- encuesta[,c(1:5,24:31,35,47:49)]

# class(df1$Timestamp)
# ymd_hms(df1$Timestamp) # no se convierten a timestamp

```

Aplicar filtros: 

- Tipo de contrato = Full-Time

```{r}
df1 %>%
  summary()
df2 <- df1 %>%
  filter(`Tipo de contrato` == "Full-Time")
df2 %>%
  head(5)
dim(df2)
glimpse(df2)
```

### Análisis exploratorio

Chequeo valores unicos y faltantes. 

```{r}
tabla2 <- df2 %>%
  gather(., 
         key = "Variables", 
         value = "Valores") %>%
  group_by(Variables) %>% 
  summarise(Valores.unicos = length(unique(Valores)), Valores.faltantes = sum(is.na(Valores)))
# ordeno la tabla por valores faltantes y luego unicos.
tabla2 %>% 
  arrange(Valores.faltantes, Valores.unicos)
```

### Chequeo Outliers Univariados

```{r}
df2[,c(3,6:9,16,17)] %>%
  pivot_longer(cols = 1:ncol(df2[,c(3,6:9,16,17)]),
         names_to = "Variables", 
         values_to  = "Valores") %>% 
  ggplot(aes(x = Variables, y = as.numeric(Valores))) + 
  geom_boxplot(alpha = 0.5) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  facet_wrap( ~ Variables, scales = "free")

# tratamiento de outliers
# corrijo datos porque entiendo se trata de un error de carga y hay información para contrastar el dato
df2$`Años en la empresa actual`[df2$`Años en la empresa actual` == 2016] <- 4
df2$`Años en la empresa actual`[df2$`Años en la empresa actual` == 88] <- 8

df2 <- df2 %>%
  mutate(`Salario mensual BRUTO (en tu moneda local)` = round(`Salario mensual BRUTO (en tu moneda local)`), `Salario mensual NETO (en tu moneda local)` = round(`Salario mensual NETO (en tu moneda local)`))


# parecen valores mal cargados (corridas las comas)
# corregir datos o eliminar para que no ensucien la base 
# ver los que tienen salario neto mayor al bruto (se trata de un error)
dim(df2 %>%
  filter(`Salario mensual BRUTO (en tu moneda local)` < `Salario mensual NETO (en tu moneda local)`) %>%
  mutate(dif = `Salario mensual NETO (en tu moneda local)` - `Salario mensual BRUTO (en tu moneda local)`)) # 125 observaciones con datos mal cargados 

# elimino las lineas erroneas por mal carga de sueldos y otro outlier
df3 <- df2 %>%
  filter(`Años en el puesto actual` < 8000, `Salario mensual BRUTO (en tu moneda local)` > `Salario mensual NETO (en tu moneda local)`)

# decidi corregir los datos en relación al salario neto 
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 2140000] <- 214000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 7470084] <- 74700
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 55008226] <- 55000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 3130025] <- 31300
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 1500000] <- 150000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 1250000] <- 125000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 900000] <- 90000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 900007] <- 90000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 700000] <- 70000
df3$`Salario mensual BRUTO (en tu moneda local)`[df3$`Salario mensual BRUTO (en tu moneda local)` == 580000] <- 58000

df3[,c(3,6:9,16:17)] %>%
  pivot_longer(cols = 1:ncol(df3[,c(3,6:9,16,17)]),
         names_to = "Variables", 
         values_to  = "Valores") %>% 
  ggplot(aes(x = Variables, y = as.numeric(Valores))) + 
  geom_boxplot(alpha = 0.5) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  facet_wrap( ~ Variables, scales = "free")

# chequeo outliers en variable salario bruto
df3 %>%
  filter(`Salario mensual BRUTO (en tu moneda local)` >= 500000)

# chequeo outliers en variable salario neto
df3 %>%
  filter(`Salario mensual BRUTO (en tu moneda local)` < 1000)

df3 <- df3 %>%
  mutate(salario_bruto = 
           case_when(`Salario mensual BRUTO (en tu moneda local)` < 1000 &
                       `Salario mensual NETO (en tu moneda local)` < 1000 ~ 
                       `Salario mensual BRUTO (en tu moneda local)`*1000, 
                     TRUE ~ `Salario mensual BRUTO (en tu moneda local)`), 
         salario_neto =           
           case_when(`Salario mensual BRUTO (en tu moneda local)` < 1000 &
                       `Salario mensual NETO (en tu moneda local)` < 1000 ~ 
                       `Salario mensual NETO (en tu moneda local)`*1000, 
                     TRUE ~ `Salario mensual NETO (en tu moneda local)`))

df3 <- df3 %>%
  mutate(salario_neto =           
           case_when(salario_neto < 1000 ~ salario_neto * 1000, 
                     TRUE ~ salario_neto))

# elimino dos registros erroneos
df3 <- df3 %>% 
  filter(salario_neto < salario_bruto)

df3 %>%
  mutate(dif = salario_neto - salario_bruto) %>%
  filter(dif < -100000, salario_neto < 100000) %>%
  select(Timestamp)

df3 %>%
  filter(salario_neto < 1000)

df3 %>%
  filter(salario_bruto > 1000000)

df3[,c(3,6:9,18:19)] %>%
  gather(.,
         key = Variables, 
         value = Valores) %>% 
  ggplot(aes(x = Variables, y = as.numeric(Valores))) + 
  geom_boxplot(alpha = 0.5) + 
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  facet_wrap( ~ Variables, scales = "free")

df3[df3$Timestamp == "1/8/2020 4:11:53","salario_bruto"] <- 45000

df3[df3$Timestamp == "1/8/2020 9:14:53","salario_neto"] <- 110000
df3[df3$Timestamp == "12/17/2019 0:16:31","salario_neto"] <- 150000
df3[df3$Timestamp == "12/22/2019 23:31:56","salario_neto"] <- 100000
df3[df3$Timestamp == "12/9/2019 15:58:28","salario_neto"] <- 120000
df3[df3$Timestamp == "1/22/2020 22:34:59","salario_neto"] <- 119000
df3[df3$Timestamp == "2/1/2020 18:37:21","salario_neto"] <- 80000

df3[df3$Timestamp == "2/2/2020 2:25:39","salario_neto"] <- 54000
df3[df3$Timestamp == "1/13/2020 14:32:52","salario_neto"] <- 50000
df3[df3$Timestamp == "1/29/2020 18:58:14","salario_neto"] <- 60000
df3[df3$Timestamp == "1/12/2020 11:49:24	","salario_neto"] <- 70000

# df3 %>%
#  filter(salario_bruto > 50000, salario_neto < 30000)
```

### Chequeo correlación

```{r}


# calculo matriz de correlacion para los registros completos (omitiendo faltantes) para variables numéricas con ambos métodos 

# pearson
matriz.correl.pe <- df3[,c(3,6:9,18:19)] %>% 
 correlate(use = "complete.obs", method = "pearson") %>% 
  shave() %>% 
  fashion()
matriz.correl.pe

# spearman
matriz.correl.sp <- df3[,c(3,6:9,18:19)] %>% 
 correlate(use = "complete.obs", method = "spearman") 
matriz.correl.sp

df3[,c(3,6:9,18:19)] %>%
     ggpairs(.,  mapping = aes(colour = df3$Estado),
        title = "Matriz de correlaciones")
        
```

```{r}
df2 %>%
  ggplot(aes(y = `Salario mensual NETO (en tu moneda local)`, x = `Salario mensual BRUTO (en tu moneda local)`)) + 
  geom_point()

df3 %>%
  ggplot(aes(y = salario_neto, x = salario_bruto)) + 
  geom_point()

df3 %>%
  ggplot(aes(y = salario_neto, x = salario_bruto, col = Estado)) + 
  geom_point()

```

```{r}
lm(salario_bruto ~ `Años de experiencia`, df3) %>%
  summary()

lm(salario_bruto ~ `Años de experiencia` + `Dónde estás trabajando` + `¿Gente a cargo?` + `Nivel de estudios alcanzado`, df3) %>%
  summary()

ggplot(df3, aes(x = `Años de experiencia`, y = salario_bruto)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```

```{r}
lm(salario_bruto ~ `Tengo`, df3) %>%
  summary()

ggplot(df3, aes(x = `Tengo` , y = salario_bruto)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```

```{r}
data_anal <- df3 %>%
  filter(grepl("Anal", `Trabajo de`)) %>% 
  filter(`Tipo de contrato` == "Full-Time")

data_anal %>%
  glimpse()
  
lm(salario_bruto ~ `Años de experiencia`, data_anal) %>%
  summary()

ggplot(data_anal, aes(x = `Años de experiencia`, y = salario_bruto)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```

```{r}
data_leader <- df3 %>%
  filter(grepl("Leader", `Trabajo de`)) %>% 
  filter(`Tipo de contrato` == "Full-Time")

data_leader %>%
  glimpse()
  
lm(salario_bruto ~ `Años de experiencia`, data_leader) %>%
  summary()

ggplot(data_leader, aes(x = `Nivel de estudios alcanzado`, y = salario_bruto)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```

```{r}
data_data <- df3 %>%
  filter(grepl("Data", `Trabajo de`))

data_data %>%
  glimpse()
  
lm(salario_bruto ~ `Años de experiencia`, data_data) %>%
  summary()

ggplot(data_data, aes(x = `Años de experiencia`, y = salario_bruto))+ 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```

```{r}
data_dev <- df3 %>%
  filter(grepl("Develop", `Trabajo de`))

data_dev %>%
  glimpse()
  
lm(salario_bruto ~ `Años de experiencia`, data_dev) %>%
  summary()

ggplot(data_dev, aes(x = `Años de experiencia`, y = salario_bruto))+ 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

# armo funciones para mostrar los datos resultantes de la regresión de forma tidy
fun1a <- function(porcion,grupo) { broom::tidy(lm(salario_bruto ~ `Años de experiencia`, data = porcion)) }
fun1b <- function(porcion,grupo) { broom::glance(lm(salario_bruto ~ `Años de experiencia`, data = porcion)) }
df_lm1 <- data_dev %>% 
  # Agrupo por tipo de propiedad
  group_by(Estado) %>%
  # Anidando
  nest() %>% 
  # Creo una columna que tenga el dataframe como resultado de la funcion
  mutate(lm1 = map(data, fun1a), glance1 = map(data, fun1b))

df_lm1 %>% 
  unnest(lm1, glance1)

# grafico recta ajustada por tipo de propiedad
ggplot(data_dev, aes(x = `Años de experiencia`, y = salario_bruto))+ 
  geom_point(alpha = 0.25) +
  stat_smooth(method = "lm", col = "red") +
  facet_wrap(~ Estado) + 
  labs(title = "") +
  theme(legend.position = 'none') 
```


```{r}
lm(salario_bruto ~ `Años de experiencia` + `Nivel de estudios alcanzado`, data_dev) %>%
  summary()

lm(salario_bruto ~ `Años de experiencia` + `Dónde estás trabajando` + `Nivel de estudios alcanzado`, data_dev) %>%
  summary()

lm(salario_bruto ~ `Años de experiencia` + `Dónde estás trabajando` + `¿Gente a cargo?` + `Nivel de estudios alcanzado`, data_dev) %>%
  summary()

ggplot(data_dev, aes(x = `Años de experiencia`, y = salario_bruto))+ 
  geom_point() +
  stat_smooth(method = "lm", col = "red")

```
